# Generated by Django 3.1.6 on 2021-02-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210201_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time_slot',
            field=models.CharField(choices=[(1, "'9:30 🚫', '10:00'"), (2, "'13:00', '13:30'")], max_length=30, null=True, verbose_name='Время'),
        ),
    ]
