# Generated by Django 3.1.6 on 2021-02-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210201_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='time_slot',
        ),
    ]
