# Generated by Django 3.1.6 on 2021-02-02 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210202_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.date(2021, 2, 2), null=True, verbose_name='время создания'),
        ),
    ]
