# Generated by Django 3.1.6 on 2021-02-02 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210202_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 0, 10, 33, 687506, tzinfo=utc), null=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lead_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 0, 10, 33, 687613, tzinfo=utc), null=True, verbose_name='время выполнения'),
        ),
    ]
