# Generated by Django 3.1.6 on 2021-02-02 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210202_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lead_time',
            field=models.DateField(default=datetime.date(2021, 2, 2), null=True, verbose_name='дата выполнения'),
        ),
    ]
