# Generated by Django 3.1.6 on 2021-02-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210202_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Заявка'), ('1', 'Забронирован'), ('2', 'Оплачен'), ('3', 'Выполняется'), ('4', 'Выполнен')], default='1', max_length=255, verbose_name='Статус'),
        ),
    ]
