# Generated by Django 3.1.6 on 2021-02-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210202_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, default='Не указано', max_length=1024, null=True, verbose_name='Описание услуги'),
        ),
    ]
